/**
 * This code was generated by Builder.io.
 */
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-chart',
  standalone: true,
  imports: [CommonModule],
  template: `
    <section class="chart">
      <div class="chart__column" *ngFor="let month of months; let i = index">
        <div class="chart__bar chart__bar--goals" [style.height.px]="goalsData[i]">
          <div class="chart__bar-inner"></div>
        </div>
        <div class="chart__bar chart__bar--sales" [style.height.px]="salesData[i]">
          <div class="chart__bar-inner"></div>
        </div>
      </div>
    </section>
  `,
  styleUrls: ['./chart.component.css']
})
export class ChartComponent {
  @Input() months: string[] = [
    'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
    'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'
  ];
  @Input() goalsData: number[] = [26, 66, 130, 130, 34, 98, 74, 66, 106, 10, 0, 0];
  @Input() salesData: number[] = [50, 114, 146, 138, 74, 82, 74, 74, 82, 82, 98, 0];
}