/**
 * This code was generated by Builder.io.
 */
import { HttpClient } from "@angular/common/http";
import { Component, OnInit } from "@angular/core";
import { CommonModule } from "@angular/common";

@Component({
  selector: "app-organic-ranking",
  standalone: true,
  imports: [CommonModule],
  templateUrl: "./organic-ranking.component.html",
  styleUrls: ["./organic-ranking.component.css"],
})
export class OrganicRankingComponent implements OnInit {
  title = "Organic Ranking";
  subtitle = "Top Keywords";
  productName = "Product Name";
  productVariant = "Product Variant";
  headers: string[] = ['Keyword', 'Organic Rank', 'Rank Change', 'Total Searches', 'Clicks This Month', 'CVR', 'Sales'];
  data: any[] = []; // Definiera data som en array

  
  constructor(private http: HttpClient) {}
  ngOnInit(): void {
    this.http.get('https://localhost:7050/KWRANKING') // Byt ut denna URL mot din egen
    .subscribe({
      next: (data) => {
        this.data = data as any[]; // Bearbeta din data här
      },
      error: (error) => {
        console.error('Error fetching data', error); // Hantera fel här
      }
    });
  }
  
}
