/**
 * This code was generated by Builder.io.
 */
import { Component } from "@angular/core";
import { CommonModule } from "@angular/common";

@Component({
  selector: "app-organic-ranking",
  standalone: true,
  imports: [CommonModule],
  templateUrl: "./organic-ranking.component.html",
  styleUrls: ["./organic-ranking.component.css"],
})
export class OrganicRankingComponent {
  title: string = "Organic Ranking";
  subtitle: string = "Top Keywords";
  productName: string = "SMELLWELL ACTIVE";
  productVariant: string = "Black Zebra";
  tableHeaders: string[] = [
    "Keyword",
    "Organic Rank",
    "Rank Change",
    "Total Searches",
    "Clicks This Month",
    "CVR",
    "Sales",
  ];
  tableData: any[] = [
    {
      keyword: "Shoe Smell",
      organicRank: 1,
      rankChange: 1,
      totalSearches: 24599,
      clicksThisMonth: 3956,
      cvr: "16%",
      sales: "$2154",
    },
  ];
}
