// /**
//  * This code was generated by Builder.io.
//  */
// import { Component } from '@angular/core';
// import { CommonModule } from '@angular/common';

// @Component({
//   selector: 'app-sales-chart',
//   templateUrl: './sales-chart.component.html',
//   styleUrls: ['./sales-chart.component.css'],
//   standalone: true,
//   imports: [CommonModule],
// })
// export class SalesChartComponent {
//   months: string[] = [
//     'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
//     'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'
//   ];

//   salesData: number[] = [50, 114, 146, 138, 74, 82, 74, 74, 82, 82, 98, 8];
//   goalsData: number[] = [26, 66, 130, 130, 34, 98, 74, 66, 106, 82, 8, 8];
// }