/**
 * This code was generated by Builder.io.
 */
import { Component, OnInit } from "@angular/core";
import { OrganicRankingComponent } from "../organic-ranking/organic-ranking.component";
import { CommonModule } from "@angular/common";

@Component({
  selector: "app-keyword-sales",
  standalone: true,
  imports: [OrganicRankingComponent, CommonModule],
  templateUrl: "./keyword-sales.component.html",
  styleUrls: ["./keyword-sales.component.css"],
})
export class KeywordSalesComponent implements OnInit {
  pageTitle: string = "Keyword & Sales";
  productCategory: string = "SMELLWELL ACTIVE";
  productName: string = "Leopard";

  constructor() {}

  ngOnInit(): void {}

  onProductClick(): void {
    console.log("Product clicked");
  }
}
