/**
 * This code was generated by Builder.io.
 */
import { HttpClient } from "@angular/common/http";
import { Component, OnInit  } from "@angular/core";
import { CommonModule } from "@angular/common";

@Component({
  selector: "app-keyword-sales",
  standalone: true,
  imports: [CommonModule],
  templateUrl: "./keyword-sales.component.html",
  styleUrls: ["./keyword-sales.component.css"],
})
export class KeywordSalesComponent implements OnInit {
  data: any;

  constructor(private http: HttpClient) {}

  ngOnInit(): void {
    this.http.get('https://localhost:7050/KWRANKING') // Byt ut denna URL mot din egen
      .subscribe({
        next: (data) => {
          this.data = data; // Bearbeta din data här
        },
        error: (error) => {
          console.error('Error fetching data', error); // Hantera fel här
        }
      });
  }
}
