/**
 * This code was generated by Builder.io.
 */
import { Component } from "@angular/core";

@Component({
  selector: "app-keyword-sales",
  standalone: true,
  templateUrl: "./keyword-sales.component.html",
  styleUrls: ["./keyword-sales.component.css"],
})
export class KeywordSalesComponent {
  // Component logic goes here
}
